version: '3'
services:
    calculator: # Main app
        image: aswwsa/flask_micro_calculator
        ports:
            - '5000:5000'
    addition:
        image: aswwsa/flask_micro_addition
    subtraction:
        image: aswwsa/flask_micro_subtraction
    multiplication:
        image: aswwsa/flask_micro_multiplication
    division:
        image: aswwsa/flask_micro_division